In [1]:
import numpy as np

Podstawy **NUMPY**

In [2]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
u = np.arange(1,89,3)
u

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [6]:
np.linspace(1,113,6)

array([  1. ,  23.4,  45.8,  68.2,  90.6, 113. ])

In [7]:
np.array([1,2,3,4,5,9,11,34,58])

array([ 1,  2,  3,  4,  5,  9, 11, 34, 58])

In [8]:
print(type(u))

<class 'numpy.ndarray'>


In [9]:
zw = [3,5,7,8,24]
type(zw)

list

In [10]:
nplist = np.array(zw)
type(nplist)

numpy.ndarray

In [15]:
l = list(nplist)
l

[3, 5, 7, 8, 24]

In [17]:
l.append(89)

In [18]:
l1 = [2,4,6,9]
l2 = [5,6,78,9,13]
l3 = [118,78,15]

l1 = l1+l2+l3
l1

[2, 4, 6, 9, 5, 6, 78, 9, 13, 118, 78, 15]

In [19]:
a = np.array(l1)
b = np.array(l2)
c = np.array(l3)

In [22]:
# a = a+b+c
# a

In [23]:
a = np.concatenate((a,b,c))
a

array([  2,   4,   6,   9,   5,   6,  78,   9,  13, 118,  78,  15,   5,
         6,  78,   9,  13, 118,  78,  15])

In [24]:
zw1 = [[1,2],[8,9]]
zw1

[[1, 2], [8, 9]]

In [25]:
zw1[0]

[1, 2]

In [26]:
zw1[0][1]

2

In [28]:
np1 = np.array(zw1)
np1

array([[1, 2],
       [8, 9]])

In [29]:
np1[0,1]

2

In [30]:
x = np.array([[3,4],[6,8]])
y = np.array([[7,11],[19,3]])

In [33]:
p = np.concatenate((x,y),axis=1)
p

array([[ 3,  4,  7, 11],
       [ 6,  8, 19,  3]])

In [34]:
prosta = np.arange(12)
prosta

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
fp = np.reshape(prosta,(2,6))
fp

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [42]:
macierz = np.array([[1,2,3,4],[9,10,11,12],[35,98,74,101]])
macierz

array([[  1,   2,   3,   4],
       [  9,  10,  11,  12],
       [ 35,  98,  74, 101]])

In [43]:
macierz[2,1]

98

In [44]:
macierz[2][1]

98

In [45]:
macierz[macierz>5]

array([  9,  10,  11,  12,  35,  98,  74, 101])

In [47]:
cv = macierz[(macierz>5) & (macierz<21)]
cv

array([ 9, 10, 11, 12])

In [48]:
parz = (macierz%2==0)
macierz[parz]

array([ 2,  4, 10, 12, 98, 74])

In [49]:
dane = np.array([1,3,8])
one = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [50]:
dane+one

array([2, 4, 9])

In [51]:
dane-one

array([0, 2, 7])

In [52]:
dane*tw

array([ 2,  6, 24])

In [53]:
dane/tw

array([0.5       , 1.5       , 2.66666667])

In [54]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [55]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [56]:
arr5 = np.arange(240).reshape((2,2,4,5,3))
arr5

array([[[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11],
          [ 12,  13,  14]],

         [[ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23],
          [ 24,  25,  26],
          [ 27,  28,  29]],

         [[ 30,  31,  32],
          [ 33,  34,  35],
          [ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44]],

         [[ 45,  46,  47],
          [ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]]],


        [[[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71],
          [ 72,  73,  74]],

         [[ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83],
          [ 84,  85,  86],
          [ 87,  88,  89]],

         [[ 90,  91,  92],
          [ 93,  94,  95],
          [ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]],

         [[105, 106, 107],
          [1

In [58]:
# prompt: utwórz wektor o długości 64 i przekształć go w tensor trójwymiarowy o dowolnym układzie

import numpy as np

# Create a vector of length 64
vector = np.arange(64)

# Reshape the vector into a 3-dimensional tensor with any desired layout
# For example, reshape into a tensor with dimensions (4, 4, 4)
tensor = vector.reshape((4, 4, 4))

# Print the resulting tensor
print(tensor)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]
