In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.10.1


In [3]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.48150963, -0.02933219, 0.01716429, -0.07409942, -0.5302864 ,
 0.62242544, -0.14129916, 0.28750846, 0.18074751, -0.4840067 ]],
 dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.06176976, 0.09708543, 0.10170616, 0.09283504, 0.05882913,
 0.18629827, 0.08680154, 0.13327733, 0.11978171, 0.06161571]],
 dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2968 - accuracy: 0.9145
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1436 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1054 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0890 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0747 - accuracy: 0.9764


In [12]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0772 - accuracy: 0.9767 - 623ms/epoch - 2ms/step


[0.07717768102884293, 0.9767000079154968]

In [13]:
probability_model=tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.41973977e-09, 2.54050919e-10, 1.69612974e-06, 3.50014197e-05,
        3.31379103e-13, 1.07820433e-07, 1.13492742e-14, 9.99962211e-01,
        7.33514582e-09, 8.86973908e-07],
       [1.31543359e-07, 2.33376636e-06, 9.99993324e-01, 3.75826085e-06,
        1.69076687e-14, 2.12614673e-08, 2.36225333e-08, 2.28142565e-13,
        4.69783259e-07, 1.70107272e-14],
       [9.37502733e-08, 9.98619318e-01, 9.92898094e-06, 5.19775494e-06,
        1.40525817e-05, 1.28625925e-05, 1.29932423e-05, 1.23915530e-03,
        8.46026378e-05, 1.76949800e-06],
       [9.99977469e-01, 1.35447306e-10, 6.87609054e-06, 1.53439910e-08,
        5.85240940e-08, 4.41363409e-06, 1.01212083e-06, 5.52362917e-06,
        4.89211942e-08, 4.66234042e-06],
       [1.82420481e-05, 1.76216357e-08, 6.46041735e-06, 2.28735733e-08,
        9.94894743e-01, 4.64845357e-07, 9.61752903e-07, 2.21797687e-04,
        3.25341745e-07, 4.85692080e-03]], dtype=float32)>